

ALTER PROCEDURE USP_CREAR_BACKUP
AS
BEGIN
	DECLARE @FILENAME VARCHAR(150);
	SET @FILENAME = 'F:\backup\EUREKABANK_' 
		+ CONVERT(VARCHAR(20),GETDATE(),112) + '.BAK';
	BACKUP DATABASE EUREKABANK 
	TO DISK = @FILENAME
	WITH FORMAT;
END;
GO

EXEC EUREKABANK..USP_CREAR_BACKUP;
GO

SELECT CONVERT(VARCHAR(20),GETDATE(),112) FECHA;
GO


