USE [master]

GO

CREATE SERVER AUDIT [SERVER_AUDIT_02]
TO FILE 
(	FILEPATH = N'F:\Auditoria\BASEDEDATOS'
	,MAXSIZE = 0 MB
	,MAX_ROLLOVER_FILES = 2147483647
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)

GO


